
kasus(0,['Ruehrbehaelter','Antrieb:elektrisch','Inhalt:entzuendlich','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(1,['Ruehrbehaelter','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(2,['Ruehrbehaelter','Antrieb:elektrisch','Inhalt:entzuendlich','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(3,['Ruehrbehaelter','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(4,['Ruehrbehaelter','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(5,['Ruehrbehaelter','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(6,['Ruehrbehaelter','Antrieb:pneumatisch','Inhalt:entzuendlich','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(7,['Ruehrbehaelter','Antrieb:pneumatisch','Inhalt:entzuendlich','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(8,['Ruehrbehaelter','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(9,['Ruehrbehaelter','Antrieb:elektrisch','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(10,['Ruehrbehaelter','Antrieb:elektrisch','FU','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(11,['Ruehrbehaelter','Antrieb:elektrisch','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(12,['Ruehrbehaelter','Antrieb:elektrisch','FU','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(13,['Ruehrbehaelter','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(14,['Ruehrbehaelter','Antrieb:pneumatisch','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(15,['Ruehrbehaelter','Antrieb:pneumatisch','Berstscheibe'],['MaschRLu','Druck']).
kasus(16,['Ruehrbehaelter','Antrieb:pneumatisch'],['MaschRLu']).
kasus(17,['Mischer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(18,['Mischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(19,['Mischer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(20,['Mischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(21,['Mischer','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(22,['Mischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(23,['Mischer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(24,['Mischer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(25,['Mischer','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(26,['Mischer','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(27,['Mischer','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(28,['Mischer','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(29,['Mischer','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(30,['Mischer','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(31,['Mischer','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(32,['Mischer','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(33,['Mischer','Antrieb:pneumatisch'],['MaschRLu']).
kasus(34,['Reaktor','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(35,['Reaktor','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(36,['Reaktor','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(37,['Reaktor','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(38,['Reaktor','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(39,['Reaktor','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(40,['Reaktor','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(41,['Reaktor','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(42,['Reaktor','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(43,['Reaktor','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(44,['Reaktor','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(45,['Reaktor','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(46,['Reaktor','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(47,['Reaktor','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(48,['Reaktor','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(49,['Reaktor','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(50,['Reaktor','Antrieb:pneumatisch'],['MaschRLu']).
kasus(51,['Leitstrahlmischer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(52,['Leitstrahlmischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(53,['Leitstrahlmischer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(54,['Leitstrahlmischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(55,['Leitstrahlmischer','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(56,['Leitstrahlmischer','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(57,['Leitstrahlmischer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(58,['Leitstrahlmischer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(59,['Leitstrahlmischer','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(60,['Leitstrahlmischer','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(61,['Leitstrahlmischer','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(62,['Leitstrahlmischer','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(63,['Leitstrahlmischer','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(64,['Leitstrahlmischer','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(65,['Leitstrahlmischer','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(66,['Leitstrahlmischer','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(67,['Leitstrahlmischer','Antrieb:pneumatisch'],['MaschRLu']).
kasus(68,['Dosierer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(69,['Dosierer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(70,['Dosierer','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(71,['Dosierer','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(72,['Dosierer','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(73,['Dosierer','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(74,['Dosierer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(75,['Dosierer','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(76,['Dosierer','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(77,['Dosierer','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(78,['Dosierer','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(79,['Dosierer','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(80,['Dosierer','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(81,['Dosierer','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(82,['Dosierer','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(83,['Dosierer','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(84,['Dosierer','Antrieb:pneumatisch'],['MaschRLu']).
kasus(85,['Abfuellanlage','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(86,['Abfuellanlage','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(87,['Abfuellanlage','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(88,['Abfuellanlage','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(89,['Abfuellanlage','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(90,['Abfuellanlage','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(91,['Abfuellanlage','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(92,['Abfuellanlage','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(93,['Abfuellanlage','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(94,['Abfuellanlage','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(95,['Abfuellanlage','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(96,['Abfuellanlage','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(97,['Abfuellanlage','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(98,['Abfuellanlage','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(99,['Abfuellanlage','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(100,['Abfuellanlage','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(101,['Abfuellanlage','Antrieb:pneumatisch'],['MaschRLu']).
kasus(102,['Silo','Mehl'],['ATEX']).
kasus(103,['Tanklager','Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck','NSR']).
kasus(104,['Tanklager','Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck','NSR','EMV']).
kasus(105,['Tanklager','Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['ATEX','Druck','NSR']).
kasus(106,['Tanklager','Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['ATEX','Druck','NSR','EMV']).
kasus(107,['Tanklager','Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich'],['ATEX','NSR']).
kasus(108,['Tanklager','Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['ATEX','NSR','EMV']).
kasus(109,['Tanklager','Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck']).
kasus(110,['Tanklager','Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['ATEX','Druck']).
kasus(111,['Tanklager','Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich'],['ATEX']).
kasus(112,['Tanklager','Pumpe','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck','NSR']).
kasus(113,['Tanklager','Pumpe','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck','NSR','EMV']).
kasus(114,['Tanklager','Pumpe','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['ATEX','Druck','NSR']).
kasus(115,['Tanklager','Pumpe','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['ATEX','Druck','NSR','EMV']).
kasus(116,['Tanklager','Pumpe','Antrieb:elektrisch'],['ATEX','NSR']).
kasus(117,['Tanklager','Pumpe','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck']).
kasus(118,['Tanklager','Pumpe','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['ATEX','Druck']).
kasus(119,['Tanklager','Pumpe','Antrieb:pneumatisch'],['ATEX']).
kasus(120,['Lagertank','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck']).
kasus(121,['Lagertank','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['ATEX','Druck']).
kasus(122,['Lagertank','Inhalt:entzuendlich'],['ATEX']).
kasus(123,['Lagertank','Druckbehaelter','Sicherheitsventil'],['Druck']).
kasus(124,['Lagertank','Druckbehaelter','Berstscheibe'],['Druck']).
kasus(125,['Lagertank'],[]).
kasus(126,['Loesungsmittelbehaelter','Fassungsvermöegen:1000L','Inhalt:Loesungsmittel','Inhalt:entzuendlich','Inhalt:wassergefaehrdend','Sicherheitsventil'],['ATEX','Druck','VAwS']).
kasus(127,['Loesungsmittelbehaelter','Fassungsvermöegen:1000L','Inhalt:Loesungsmittel','Inhalt:entzuendlich','Inhalt:wassergefaehrdend','Berstscheibe'],['ATEX','Druck','VAwS']).
kasus(128,['Loesungsmittelbehaelter','Fassungsvermöegen:1000L','Inhalt:Loesungsmittel','Inhalt:entzuendlich','Inhalt:wassergefaehrdend'],['ATEX','VAwS']).
kasus(129,['Reaktor','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRL','Druck','NSR']).
kasus(130,['Reaktor','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRL','Druck','NSR','EMV']).
kasus(131,['Reaktor','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRL','Druck','NSR']).
kasus(132,['Reaktor','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRL','Druck','NSR','EMV']).
kasus(133,['Reaktor','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(134,['Reaktor','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRL','Druck']).
kasus(135,['Reaktor','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRL','Druck']).
kasus(136,['Reaktor','Antrieb:pneumatisch'],['MaschRL']).
kasus(137,['Reaktor','Druckbehaelter','Sicherheitsventil'],['Druck']).
kasus(138,['Reaktor','Druckbehaelter','Berstscheibe'],['Druck']).
kasus(139,['Reaktor'],[]).
kasus(140,['Mischer','Inhalt:Loesungsmittel','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','VAwS']).
kasus(141,['Mischer','Inhalt:Loesungsmittel','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV','VAwS']).
kasus(142,['Mischer','Inhalt:Loesungsmittel','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','VAwS']).
kasus(143,['Mischer','Inhalt:Loesungsmittel','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV','VAwS']).
kasus(144,['Mischer','Inhalt:Loesungsmittel','Antrieb:elektrisch'],['MaschRLu','ATEX','NSR','VAwS']).
kasus(145,['Mischer','Inhalt:Loesungsmittel','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','VAwS']).
kasus(146,['Mischer','Inhalt:Loesungsmittel','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','VAwS']).
kasus(147,['Mischer','Inhalt:Loesungsmittel','Antrieb:pneumatisch'],['MaschRLu','ATEX','VAwS']).
kasus(148,['Mischer','Inhalt:Loesungsmittel','Druckbehaelter','Sicherheitsventil'],['ATEX','Druck','VAwS']).
kasus(149,['Mischer','Inhalt:Loesungsmittel','Druckbehaelter','Berstscheibe'],['ATEX','Druck','VAwS']).
kasus(150,['Mischer','Inhalt:Loesungsmittel'],['ATEX','VAwS']).
kasus(151,['Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR']).
kasus(152,['Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(153,['Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR']).
kasus(154,['Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck','NSR','EMV']).
kasus(155,['Pumpe','Antrieb:elektrisch','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR']).
kasus(156,['Pumpe','Antrieb:elektrisch','FU','Inhalt:entzuendlich'],['MaschRLu','ATEX','NSR','EMV']).
kasus(157,['Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Sicherheitsventil'],['MaschRLu','ATEX','Druck']).
kasus(158,['Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich','Druckbehaelter','Berstscheibe'],['MaschRLu','ATEX','Druck']).
kasus(159,['Pumpe','Antrieb:pneumatisch','Inhalt:entzuendlich'],['MaschRLu','ATEX']).
kasus(160,['Pumpe','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR']).
kasus(161,['Pumpe','Antrieb:elektrisch','FU','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck','NSR','EMV']).
kasus(162,['Pumpe','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR']).
kasus(163,['Pumpe','Antrieb:elektrisch','FU','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck','NSR','EMV']).
kasus(164,['Pumpe','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(165,['Pumpe','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['MaschRLu','Druck']).
kasus(166,['Pumpe','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['MaschRLu','Druck']).
kasus(167,['Pumpe','Antrieb:pneumatisch'],['MaschRLu']).
kasus(168,['(Hand)Bohrmaschiene','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(169,['(Hand)Bohrmaschiene','Antrieb:pneumatisch'],['MaschRL']).
kasus(170,['Schleifmaschine','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(171,['Schleifmaschine','Antrieb:pneumatisch'],['MaschRL']).
kasus(172,['Drehbank','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(173,['Drehbank','Antrieb:pneumatisch'],['MaschRL']).
kasus(174,['Drehmaschine','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(175,['Drehmaschine','Antrieb:pneumatisch'],['MaschRL']).
kasus(176,['Tellerdrehmaschine','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(177,['Tellerdrehmaschine','Antrieb:pneumatisch'],['MaschRL']).
kasus(178,['Walze','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(179,['Walze','Antrieb:pneumatisch'],['MaschRL']).
kasus(180,['Pilgerwalze','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(181,['Pilgerwalze','Antrieb:pneumatisch'],['MaschRL']).
kasus(182,['Walzwerk','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(183,['Walzwerk','Antrieb:pneumatisch'],['MaschRL']).
kasus(184,['Walzmaschiene','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(185,['Walzmaschiene','Antrieb:pneumatisch'],['MaschRL']).
kasus(186,['Abkantbank','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(187,['Abkantbank','Antrieb:pneumatisch'],['MaschRL']).
kasus(188,['Schere','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(189,['Schere','Antrieb:pneumatisch'],['MaschRL']).
kasus(190,['Schlagschere','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(191,['Schlagschere','Antrieb:pneumatisch'],['MaschRL']).
kasus(192,['Fraese','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(193,['Fraese','Antrieb:pneumatisch'],['MaschRL']).
kasus(194,['Portalfraese','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(195,['Portalfraese','Antrieb:pneumatisch'],['MaschRL']).
kasus(196,['Werkzeugmaschiene','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(197,['Werkzeugmaschiene','Antrieb:pneumatisch'],['MaschRL']).
kasus(198,['Presse','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(199,['Presse','Antrieb:pneumatisch'],['MaschRL']).
kasus(200,['Hammer','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(201,['Hammer','Antrieb:pneumatisch'],['MaschRL']).
kasus(202,['Schmiedehammer','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(203,['Schmiedehammer','Antrieb:pneumatisch'],['MaschRL']).
kasus(204,['Tiefziehpresse','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(205,['Tiefziehpresse','Antrieb:pneumatisch'],['MaschRL']).
kasus(206,['Kuehlung','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(207,['Kuehlung','Antrieb:pneumatisch'],['MaschRLu']).
kasus(208,['Rueckkuehlwerk','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(209,['Rueckkuehlwerk','Antrieb:pneumatisch'],['MaschRLu']).
kasus(210,['Rueckkuehler','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(211,['Rueckkuehler','Antrieb:pneumatisch'],['MaschRLu']).
kasus(212,['Kuehlmaschiene','Antrieb:elektrisch'],['NSR']).
kasus(213,['Kuehlmaschiene','Antrieb:pneumatisch'],[]).
kasus(214,['Kaeltemaschiene','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['Druck','NSR']).
kasus(215,['Kaeltemaschiene','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['Druck','NSR']).
kasus(216,['Kaeltemaschiene','Antrieb:elektrisch'],['NSR']).
kasus(217,['Kaeltemaschiene','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['Druck']).
kasus(218,['Kaeltemaschiene','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['Druck']).
kasus(219,['Kaeltemaschiene','Antrieb:pneumatisch'],[]).
kasus(220,['Kuehlagregat','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['Druck','NSR']).
kasus(221,['Kuehlagregat','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['Druck','NSR']).
kasus(222,['Kuehlagregat','Antrieb:elektrisch'],['NSR']).
kasus(223,['Kuehlagregat','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['Druck']).
kasus(224,['Kuehlagregat','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['Druck']).
kasus(225,['Kuehlagregat','Antrieb:pneumatisch'],[]).
kasus(226,['Kaelteagregat','Antrieb:elektrisch','Druckbehaelter','Sicherheitsventil'],['Druck','NSR']).
kasus(227,['Kaelteagregat','Antrieb:elektrisch','Druckbehaelter','Berstscheibe'],['Druck','NSR']).
kasus(228,['Kaelteagregat','Antrieb:elektrisch'],['NSR']).
kasus(229,['Kaelteagregat','Antrieb:pneumatisch','Druckbehaelter','Sicherheitsventil'],['Druck']).
kasus(230,['Kaelteagregat','Antrieb:pneumatisch','Druckbehaelter','Berstscheibe'],['Druck']).
kasus(231,['Kaelteagregat','Antrieb:pneumatisch'],[]).
kasus(232,['Ofen','Antrieb:elektrisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRL','NSR']).
kasus(233,['Ofen','Antrieb:elektrisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRL','NSR']).
kasus(234,['Ofen','Antrieb:pneumatisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRL','NSR']).
kasus(235,['Ofen','Antrieb:pneumatisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRL']).
kasus(236,['Ofen','beheizt:elektrisch','Temperaturbegrenzer'],['NSR']).
kasus(237,['Ofen','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],[]).
kasus(238,['Temperofen','Antrieb:elektrisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRL','NSR']).
kasus(239,['Temperofen','Antrieb:elektrisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRL','NSR']).
kasus(240,['Temperofen','Antrieb:pneumatisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRL','NSR']).
kasus(241,['Temperofen','Antrieb:pneumatisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRL']).
kasus(242,['Temperofen','beheizt:elektrisch','Temperaturbegrenzer'],['NSR']).
kasus(243,['Temperofen','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],[]).
kasus(244,['Extruder','Antrieb:elektrisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(245,['Extruder','Antrieb:elektrisch','FU','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR','EMV']).
kasus(246,['Extruder','Antrieb:elektrisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(247,['Extruder','Antrieb:elektrisch','FU','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR','EMV']).
kasus(248,['Extruder','Antrieb:pneumatisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(249,['Extruder','Antrieb:pneumatisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(250,['Extruder','Antrieb:elektrisch'],['MaschRLu','Druck','NSR']).
kasus(251,['Extruder','Antrieb:pneumatisch'],['MaschRLu','Druck','NSR']).
kasus(252,['Granulator','Antrieb:elektrisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(253,['Granulator','Antrieb:elektrisch','FU','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR','EMV']).
kasus(254,['Granulator','Antrieb:elektrisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(255,['Granulator','Antrieb:elektrisch','FU','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR','EMV']).
kasus(256,['Granulator','Antrieb:pneumatisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(257,['Granulator','Antrieb:pneumatisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(258,['Granulator','Antrieb:elektrisch'],['MaschRLu','Druck','NSR']).
kasus(259,['Granulator','Antrieb:pneumatisch'],['MaschRLu','Druck','NSR']).
kasus(260,['Zentrifuge','Antrieb:elektrisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(261,['Zentrifuge','Antrieb:elektrisch','FU','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR','EMV']).
kasus(262,['Zentrifuge','Antrieb:elektrisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(263,['Zentrifuge','Antrieb:elektrisch','FU','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR','EMV']).
kasus(264,['Zentrifuge','Antrieb:pneumatisch','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','Druck','NSR']).
kasus(265,['Zentrifuge','Antrieb:pneumatisch','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu','Druck','NSR']).
kasus(266,['Zentrifuge','Antrieb:elektrisch'],['MaschRLu','Druck','NSR']).
kasus(267,['Zentrifuge','Antrieb:pneumatisch'],['MaschRLu','Druck','NSR']).
kasus(268,['Trockner','beheizt:elektrisch','Temperaturbegrenzer'],['MaschRLu','NSR']).
kasus(269,['Trockner','beheizt:Gas','Temperaturbegrenzer','Gaswarnanlage'],['MaschRLu']).
kasus(270,['Foerderband','Antrieb:elektrisch'],['MaschRL','NSR']).
kasus(271,['Foerderband','Antrieb:pneumatisch'],['MaschRL']).
kasus(272,['Becherwerk','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(273,['Becherwerk','Antrieb:pneumatisch'],['MaschRLu']).
kasus(274,['Elevator','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(275,['Elevator','Antrieb:pneumatisch'],['MaschRLu']).
kasus(276,['Foerderer','Antrieb:elektrisch'],['MaschRLu','NSR']).
kasus(277,['Foerderer','Antrieb:pneumatisch'],['MaschRLu']).
kasus(278,['Lampe'],['NSR']).
